version: '2'
services:
  postgres:
    image: postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    ulimits:
      nproc: 65535
      nofile:
        soft: 65536
        hard: 65536
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
    user: postgres
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./conf:/etc/postgresql
